# make nginx (sudo docker-compose up -d nginx)  - Запускаем контейнера nginx, php, mysql

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8085:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    depends_on:
      - php
      - mysql
      - redis
    restart: "always"

  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
  mysql:
    image: mysql:8.0
    ports: 
      - "3316:3306"
    env_file:
      - env/mysql.env
    volumes:
      - db_data:/var/lib/mysql
    restart: "always"

  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/laravel

  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
    - ./src:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]

  node:
    image: node:current-alpine
    volumes:
      - ./src:/var/www/laravel
    working_dir: /var/www/laravel

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: "always"

  
volumes:
  db_data:
